version: "2"
services:
  #APP
  app:
    build: .
    container_name: bank-api
    hostname: bank-api
    tty: true
    privileged: false
    restart: on-failure
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "4001:4001"